server:
  port: 5556
  servlet:
    context-path: /cloud

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: registration
          uri: http://localhost:8170
          predicates:
            - Path=/client1/**
        #          filters:
        #            - RewritePath=/registration, /auth
        #        - id: registration2
        #          uri: http://localhost:8171
        #          predicates:
        #              - Path=/client2/**
        - id: registration3
          uri: lb://ms-client2-hystrix
          predicates:
            - Path=/client2/**